"""
Strategy Agent Node

This module contains the strategy agent node for the proposal analysis workflow.
This agent generates a strategic recommendation based on the entire analysis.
"""

import logging
import os
import time
from typing import Dict, Any, List
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from agent_state import AgentState
from langfuse_setup import trace_llm_call
from .utils import extract_next_steps_from_text

# Configure logging
logger = logging.getLogger('agent_nodes.strategy_agent')

def strategy_agent(state: AgentState) -> AgentState:
    """Agent Node: Generate strategic recommendation.
    
    This agent takes the entire analysis and generates a strategic recommendation
    for the proposal. It provides a summary of the analysis, a recommendation,
    and next steps.
    
    Args:
        state: The current state of the agent
        
    Returns:
        Updated state with strategic recommendation and next steps
    """
    try:
        logger.info("==== STRATEGY AGENT ====")
        logger.info("Generating strategic recommendation...")
        
        # Extract analysis results
        claims_evidence = state.get("claims_evidence", [])
        hypotheses = state.get("hypotheses", [])
        signals = state.get("signals", [])
        critique = state.get("critique", "")
        tasks = state.get("tasks", [])
        blockers = state.get("blockers", [])
        arguments = state.get("arguments", {"for_proposal": [], "against": []})
        metadata = state.get("metadata", {})
        
        # Debug logging for state contents
        logger.info(f"State keys: {list(state.keys())}")
        logger.info(f"Arguments in state: {arguments}")
        logger.info(f"Hypotheses count: {len(hypotheses)}")
        
        # Check if arguments are nested in another key
        for key in state.keys():
            if isinstance(state[key], dict) and "for_proposal" in state[key]:
                logger.info(f"Found arguments in key: {key}")
                logger.info(f"Arguments: {state[key]}")
                arguments = state[key]
        
        # Prepare the prompt for the strategy agent
        system_prompt = """You are a governance proposal strategy agent. Your task is to:
1. Synthesize the entire analysis of the proposal
2. Generate a strategic recommendation based on the analysis
3. Provide a summary of the key points from the analysis
4. Outline specific next steps for stakeholders

Output a JSON object with:
- summary: Overall summary of the analysis
- recommendation: Strategic recommendation for the proposal
- next_steps: Array of specific next steps for stakeholders
"""
        
        # Prepare analysis summary for the prompt
        # Include key claims (limited to 3 for brevity)
        claims_summary = "\n".join([
            f"- {claim_obj.get('claim', '')} (Confidence: {claim_obj.get('confidence', 0.5)})"
            for claim_obj in claims_evidence[:3] if claim_obj.get('claim')
        ])
        if not claims_summary:
            claims_summary = "No specific claims identified"
            
        # Include key hypotheses (limited to 3 for brevity)
        hypotheses_summary = "\n".join([
            f"- {hyp.get('hypothesis', '')} ({hyp.get('type', 'implication')})"
            for hyp in hypotheses[:3] if hyp.get('hypothesis')
        ])
        if not hypotheses_summary:
            hypotheses_summary = "No specific hypotheses generated"
            
        # Include key signals (limited to 3 for brevity)
        signals_summary = "\n".join([
            f"- {signal.get('description', '')} ({signal.get('severity', 'medium')})"
            for signal in signals[:3] if signal.get('description')
        ])
        if not signals_summary:
            signals_summary = "No significant signals detected"
        
        # Include tasks, blockers, and arguments as before
        tasks_summary = "\n".join([
            f"- {task.get('description', '')} (Priority: {task.get('priority', 'medium')})"
            for task in tasks[:3]  # Limit to 3 tasks
        ])
        if not tasks_summary:
            tasks_summary = "No specific tasks identified"
        
        blockers_summary = "\n".join([f"- {blocker}" for blocker in blockers[:3]])
        if not blockers_summary:
            blockers_summary = "No significant blockers identified"
        
        # IMPORTANT: Arguments MUST be generated by OpenRouter ChatGPT-4o (in the hypothesizer.py module)
        # We should never use hardcoded arguments or simply fetch them without LLM processing
        # This ensures high-quality, nuanced arguments for governance proposals
        for_args = arguments.get("for_proposal", [])
        against_args = arguments.get("against", [])
        
        # If arguments are missing, try to extract them from hypotheses
        if not for_args or not against_args or len(for_args) < 2 or len(against_args) < 2:
            logger.warning("Arguments missing or incomplete, attempting to extract from hypotheses")
            
            # Extract arguments from hypotheses based on impact and likelihood
            for_args_from_hypotheses = []
            against_args_from_hypotheses = []
            
            for hyp in hypotheses:
                hyp_text = hyp.get("hypothesis", "")
                hyp_type = hyp.get("type", "")
                impact = hyp.get("impact", 0.5)
                likelihood = hyp.get("likelihood", 0.5)
                
                if not hyp_text:
                    continue
                    
                if hyp_type == "benefit" or (hyp_type == "implication" and impact > 0.6 and likelihood > 0.5):
                    for_args_from_hypotheses.append(hyp_text)
                elif hyp_type == "risk" or (hyp_type == "implication" and impact < 0.4 and likelihood > 0.5):
                    against_args_from_hypotheses.append(hyp_text)
            
            # Use extracted arguments if original arguments are missing or insufficient
            if (not for_args or len(for_args) < 2) and for_args_from_hypotheses:
                if not for_args:
                    for_args = for_args_from_hypotheses
                else:
                    # Supplement existing arguments
                    for arg in for_args_from_hypotheses:
                        if arg not in for_args:
                            for_args.append(arg)
                logger.info(f"Extracted/supplemented supporting arguments from hypotheses, now have {len(for_args)}")
                
            if (not against_args or len(against_args) < 2) and against_args_from_hypotheses:
                if not against_args:
                    against_args = against_args_from_hypotheses
                else:
                    # Supplement existing arguments
                    for arg in against_args_from_hypotheses:
                        if arg not in against_args:
                            against_args.append(arg)
                logger.info(f"Extracted/supplemented opposing arguments from hypotheses, now have {len(against_args)}")
                
            # Ensure we always have balanced arguments with fallbacks if needed
            fallback_for = [
                "The proposal may improve the protocol's functionality or efficiency.",
                "The proposal could address existing security vulnerabilities.",
                "The proposal might enhance user experience or accessibility."
            ]
            
            fallback_against = [
                "The proposal may introduce new security risks or vulnerabilities.",
                "The implementation could be complex and resource-intensive.",
                "The changes might not be backward compatible with existing systems."
            ]
            
            # Ensure at least 2 arguments for each side
            if not for_args or len(for_args) < 2:
                logger.warning("Still missing sufficient FOR arguments, using fallbacks")
                if not for_args:
                    for_args = fallback_for
                else:
                    # Add fallbacks until we have at least 2
                    for arg in fallback_for:
                        if arg not in for_args:
                            for_args.append(arg)
                        if len(for_args) >= 2:
                            break
            
            if not against_args or len(against_args) < 2:
                logger.warning("Still missing sufficient AGAINST arguments, using fallbacks")
                if not against_args:
                    against_args = fallback_against
                else:
                    # Add fallbacks until we have at least 2
                    for arg in fallback_against:
                        if arg not in against_args:
                            against_args.append(arg)
                        if len(against_args) >= 2:
                            break
        
        # Format arguments for display
        for_arguments = "\n".join([f"- {arg}" for arg in for_args[:3]]) if for_args else "No supporting arguments available"
        against_arguments = "\n".join([f"- {arg}" for arg in against_args[:3]]) if against_args else "No opposing arguments available"
        
        # Log a warning if arguments are still missing
        if not for_args or not against_args:
            logger.warning(f"Still missing arguments: {len(for_args)} for, {len(against_args)} against")
            logger.warning("Arguments should be generated by OpenRouter ChatGPT-4o, not hardcoded.")
        else:
            logger.info(f"Using {len(for_args)} supporting arguments and {len(against_args)} opposing arguments")

        
        # Use a very minimal user prompt to reduce token count
        user_prompt = f"Proposal: {metadata.get('title', 'Governance proposal')}"
        
        # Prepare a minimal prompt for the strategy agent to reduce token count
        system_prompt = "Generate a strategic recommendation with next steps."
        
        # Initialize the language model - using OpenRouter with GPT-4o for consistency with argument generation
        model = os.getenv("WEI_AGENT_STRATEGY_MODEL", "openai/gpt-4o")
        temperature = float(os.getenv("WEI_AGENT_STRATEGY_TEMPERATURE", "0.3"))
        
        logger.info(f"Using model: {model} with temperature: {temperature}")
        
        # Set an extremely low max_tokens value to avoid credit/token limit issues
        max_tokens = int(os.getenv("WEI_AGENT_STRATEGY_MAX_TOKENS", "20"))
        logger.info(f"Using max_tokens: {max_tokens}")
        
        # Ensure we're using OpenRouter with GPT-4o for consistency with argument generation
        llm = ChatOpenAI(
            model=model,  # Should be openai/gpt-4o
            temperature=temperature,
            max_tokens=max_tokens,  # Limit token usage
            api_key=os.getenv("WEI_AGENT_OPEN_ROUTER_API_KEY"),
            base_url="https://openrouter.ai/api/v1"
        )
        
        # Log a warning if we're not using GPT-4o
        if "gpt-4o" not in model:
            logger.warning(f"Not using GPT-4o as requested. Using {model} instead.")
            logger.warning("Check WEI_AGENT_STRATEGY_MODEL environment variable for consistency with argument generation.")

        
        # Prepare messages for the LLM
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt)
        ]
        
        # Start timing for latency measurement
        start_time = time.time()
        
        # Call the LLM with error handling
        try:
            response = llm.invoke(messages)
            
            # Calculate latency in milliseconds
            latency_ms = int((time.time() - start_time) * 1000)
            
            # Extract the strategy from the response
            response_text = response.content
            logger.debug(f"Strategy agent response: {response_text}")
            
            # Trace the LLM call if tracing is available
            try:
                trace_llm_call(
                    model_name=model,
                    prompt=user_prompt,  # Add the missing prompt parameter
                    completion=response_text,  # Add the missing completion parameter
                    latency_ms=latency_ms,
                    metadata={
                        "proposal_title": metadata.get('title', 'Untitled')
                    }
                )
            except Exception as trace_error:
                logger.warning(f"Error in tracing: {str(trace_error)}")
        except Exception as e:
            logger.error(f"Error during LLM call: {str(e)}")
            # Create minimal response that can be processed
            response_text = """{
                "summary": "The proposal requires careful consideration of both benefits and risks.",
                "recommendation": "Proceed with caution after addressing key concerns.",
                "next_steps": ["Review technical implementation details", "Assess security implications", "Gather community feedback"]
            }"""
            logger.info("Using minimal fallback response due to LLM error")
        
        # Parse the response to extract strategy
        import json
        import re
        
        # Try to extract JSON from the response
        json_match = re.search(r'```(?:json)?\s*([\s\S]*?)\s*```', response_text)
        summary = ""
        recommendation = ""
        next_steps = []
        
        if json_match:
            try:
                response_json = json.loads(json_match.group(1))
                summary = response_json.get("summary", "")
                recommendation = response_json.get("recommendation", "")
                next_steps = response_json.get("next_steps", [])
                logger.info(f"Successfully parsed strategy from JSON response")
            except json.JSONDecodeError:
                logger.warning("Failed to parse JSON from response")
                # Fallback to pattern matching
                summary_match = re.search(r'summary"?\s*:?\s*"(.*?)"', response_text, re.DOTALL)
                if summary_match:
                    summary = summary_match.group(1)
                
                recommendation_match = re.search(r'recommendation"?\s*:?\s*"(.*?)"', response_text, re.DOTALL)
                if recommendation_match:
                    recommendation = recommendation_match.group(1)
                
                next_steps = extract_next_steps_from_text(response_text)
        else:
            # Fallback to pattern matching
            paragraphs = response_text.split("\n\n")
            
            # Try to find summary and recommendation in paragraphs
            for para in paragraphs:
                if "summary" in para.lower() or "overview" in para.lower():
                    summary = para
                elif "recommend" in para.lower() or "strategy" in para.lower():
                    recommendation = para
            
            # Extract next steps
            next_steps = extract_next_steps_from_text(response_text)
        
        # If we still don't have a summary or recommendation, use the first and second paragraphs
        if not summary and len(paragraphs) > 0:
            summary = paragraphs[0]
        
        if not recommendation and len(paragraphs) > 1:
            recommendation = paragraphs[1]
        
        # Ensure we have at least one next step
        if not next_steps:
            next_steps = ["Review the proposal in more detail", "Consult with subject matter experts"]
        
        # Update the state with strategy
        state["summary"] = summary
        state["recommendation"] = recommendation
        state["next_steps"] = next_steps
        
        logger.info(f"Generated strategic recommendation with {len(next_steps)} next steps")
        
        return state
    except Exception as e:
        logger.error(f"Error in strategy agent: {str(e)}", exc_info=True)
        state["summary"] = f"Error in strategy agent: {str(e)}"
        state["recommendation"] = "Unable to generate recommendation due to an error"
        state["next_steps"] = ["Review the proposal manually", "Investigate the error in the strategy agent"]
        return state
