name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Please provide a clear description of the issue
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What needs to be done to resolve this issue?
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: check one
        - label: check two
