name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        
        Please provide a clear and detailed description of the issue you're experiencing.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        ### Description
        Summary about the issue explaining motivation/problems and all the features needed.
    validations:
      required: true
  
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      value: |
        ### Acceptance Criteria
        
        * [ ] Check One
        * [ ] Check Two
    validations:
      required: true
      
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any additional context, environment details, or screenshots that might help
      value: |
        ### Additional Information
        
        * Browser: Chrome 115.0.5790.171
        * OS: macOS 13.4
        * Error from console: `Uncaught SyntaxError: Unexpected token '`' in JSON at position 42`
        
        ![Screenshot of the error](URL_TO_SCREENSHOT)
    validations:
      required: false
