name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request
        
        Please provide a clear and detailed description of the feature you'd like to see implemented.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        Summary about the issue explaining motivation/problems and all the features needed.
    validations:
      required: true
  
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      value: |
        Description of the tentative solution or ideas you have to discuss or solve the issue.
        * [ ] check one
        * [ ] check two
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered (Optional)
      description: Have you considered any alternative solutions or features?
      placeholder: |
        ### Alternatives Considered
        
        * alternative one
        * alternative two
    validations:
      required: false
