name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request
        
        Please provide a clear and detailed description of the feature you'd like to see implemented.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        ### Description
        
        Instead of full OAuth integration, we will add a **very simple authentication flow**:
        
        * When a user visits the platform, ask them to enter their **name**.
        * Use ChatGPT to search and retrieve publicly available information about this user (background, social links, interests).
        * Generate a **minimal profile** for the user based on that information.
        * Store this profile in the session so it can be used across the platform.
        * This approach avoids complex OAuth setup and keeps the flow lightweight.
    validations:
      required: true
  
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        ### Acceptance Criteria
        
        * [ ] Prompt user for their name on first visit.
        * [ ] Query ChatGPT with the given name to retrieve public information.
        * [ ] Display a greeting and minimal profile (name, enriched details).
        * [ ] Store the profile in the session for the duration of the visit.
        * [ ] Authenticated users (via name input) can access proposal analysis features.
        * [ ] Handle edge cases (empty input, no info found, multiple matches).
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: |
        ### Alternatives Considered
        
        * Full OAuth integration was considered but rejected due to complexity and timeline constraints.
        * Using a simple password system was considered but offers no real security benefit over the proposed solution.
    validations:
      required: false
